### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by hnisonoff** [google-deepmind/PGMax#8]
I am using PGMax in a loop where I am iteratively creating a factor graph and running max-product BP. I am noticing that as I do this, the GPU memory keeps increasing until I run out of memory. 

Do you have any advice for debugging this issue? I wonder if it is some issue with newer versions of Jax? I am using Jax 0.4.34.  Thanks!

**Comment by StannisZhou** [comment]
Hi @hnisonoff , have you tried setting `XLA_PYTHON_CLIENT_ALLOCATOR=platform`, following https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html ?

If that does not resolve the issue, could you share a minimal script that reproduces the issue?

**Comment by hnisonoff** [comment]
Hi @StannisZhou , thank you for the help! Yes I have tried that. 

Here is an example script. Let me know how I can help!

```
import os
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"]="platform"

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

from pgmax import fgraph, fgroup, infer, vgroup

def potts_to_fg_debug():
    '''
    Create a new factor graph
    '''
    num_vars = 100
    variables = vgroup.NDVarArray(num_states=21, shape=(num_vars, ))
    fg = fgraph.FactorGraph(variable_groups=[variables])
    unaries = fgroup.EnumFactorGroup(
        variables_for_factors=[[v] for v in variables],
        factor_configs=np.arange(21)[:, None],
        log_potentials=np.random.randn(num_vars, 21))

    pairs_of_vars = [[variables[i], variables[j]] for i in range(num_vars-1) for j in range(i+1, num_vars)]
    pairs_of_indices = np.asarray([[i, j] for i in range(num_vars-1) for j in range(i+1, num_vars)])
    pairwise_factors = fgroup.PairwiseFactorGroup(
        variables_for_factors=pairs_of_vars,
        log_potential_matrix=np.random.randn(100, 100, 21, 21)[pairs_of_indices[:, 0], pairs_of_indices[:, 1]])
    fg.add_factors([unaries, pairwise_factors])
    return fg


def run_max_product_bp_debug(num_iters=100, damping=0.5):
    '''
    Run max-product bp
    '''
    fg = potts_to_fg_debug()
    bp = infer.build_inferer(fg.bp_state, backend="bp")
    bp_arrays = bp.init()
    bp_arrays, msgs_deltas = bp.run_with_diffs(
        bp_arrays, num_iters=num_iters, damping=damping, temperature=0.0
    )
    beliefs = bp.get_beliefs(bp_arrays)
    map_states = infer.decode_map_states(beliefs)
    res = list(np.asarray(map_states[fg.variable_groups[0]]))
    return res


for _ in tqdm(range(1000)):
    x = run_max_product_bp_debug()
```

**Comment by hnisonoff** [comment]
If I run this script and watch `nvidia-smi` I can see the GPU memory climb.

**Comment by StannisZhou** [comment]
It seems to be related to jitting.

If you update your `run_max_product_bp_debug` function to be the following

```
@jax.jit
def run_max_product_bp_debug(num_iters=100, damping=0.5):
    '''
    Run max-product bp
    '''
    fg = potts_to_fg_debug()
    bp = infer.build_inferer(fg.bp_state, backend="bp")
    bp_arrays = bp.init()
    bp_arrays, msgs_deltas = bp.run_with_diffs(
        bp_arrays, num_iters=num_iters, damping=damping, temperature=0.0
    )
    beliefs = bp.get_beliefs(bp_arrays)
    map_states = infer.decode_map_states(beliefs)
    res = map_states[fg.variable_groups[0]]
    return res
```

It is 40x faster and the GPU memory usage no longer climbs.

**Comment by hnisonoff** [comment]
Thank you and sorry if this is obvious -- I am new to JAX. 

My actual code takes in a new factor graph, `fg`, of varying sizes. 

Do you have suggestions for how to jit such a function?
```
def run_max_product_bp(fg, num_iters=100, damping=0.5):
    bp = infer.build_inferer(fg.bp_state, backend="bp")
    bp_arrays = bp.init()
    bp_arrays, msgs_deltas = bp.run_with_diffs(
        bp_arrays, num_iters=num_iters, damping=damping, temperature=0.0
    )
    beliefs = bp.get_beliefs(bp_arrays)
    map_states = infer.decode_map_states(beliefs)
    res = list(map_states[fg.variable_groups[0]])
    return res
```


Currently I get the following error:

```
---------------------------------------------------------------------------
TracerBoolConversionError                 Traceback (most recent call last)
Cell In[37], line 18
     14 sub_model = get_reduced_potts(recomb_model, rl, block_idx,
     15                               parent_idx, 'cpu', entropy_reg)
     17 fg = potts_to_fg(sub_model)
---> 18 new_seq = run_max_product_bp(fg, num_iters=100, damping=0.5)
     20 with torch.no_grad():
     21     score_before = sub_model(F.one_hot(torch.tensor(seq_to_update).long(), num_classes=21).float().unsqueeze(0)).item()

    [... skipping hidden 11 frame]

Cell In[36], line 25, in run_max_product_bp(fg, num_iters, damping)
     23 bp = infer.build_inferer(fg.bp_state, backend="bp")
     24 bp_arrays = bp.init()
---> 25 bp_arrays, msgs_deltas = bp.run_with_diffs(
     26     bp_arrays, num_iters=num_iters, damping=damping, temperature=0.0
     27 )
     28 beliefs = bp.get_beliefs(bp_arrays)
     29 map_states = infer.decode_map_states(beliefs)

File /data/mambaforge/envs/hunter_play/lib/python3.10/site-packages/pgmax/infer/bp.py:142, in BP.<locals>.run_with_diffs(bp_arrays, num_iters, damping, temperature)
    137   return new_msgs, msgs_delta
    139 # Scan can have significant overhead for a small number of iterations
    140 # if not JITed.  Running one it at a time is a common use-case
    141 # for checking convergence, so specialize that case.
--> 142 if num_iters > 1:
    143   ftov_msgs, msgs_deltas = jax.lax.scan(update, ftov_msgs, None, num_iters)
    144 else:

    [... skipping hidden 1 frame]

File /data/mambaforge/envs/hunter_play/lib/python3.10/site-packages/jax/_src/core.py:1547, in concretization_function_error.<locals>.error(self, arg)
   1546 def error(self, arg):
-> 1547   raise TracerBoolConversionError(arg)

TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[].
The error occurred while tracing the function run_max_product_bp at /tmp/ipykernel_3902626/3874832280.py:21 for jit. This value became a tracer due to JAX operations on these lines:

  operation a:bool[] = gt b c
    from line /tmp/ipykernel_3902626/3874832280.py:25 (run_max_product_bp)
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerBoolConversionError

```

**Comment by hnisonoff** [comment]
I fixed the error by forcing `num_iters` to always be 100. However, with `fg` passed as an argument, it seems that the effect of jit-ing is no longer happening and memory accumulates.

**Comment by hnisonoff** [comment]
I think I figured it out. Will update shortly. Thanks!

**Comment by StannisZhou** [comment]
Your error above can be fixed by specifying `num_iters` to be a static argument. You might also need to specify `fg` to be a static argument. However when your static argument changes, you would trigger re-jitting which in some cases might be expensive. For the same set of static arguments jitting will happen only once and is cached.

**Comment by hnisonoff** [comment]
Got it! I was able to make the function take in numpy arrays that are then used to create the factor graph. All is working! Thank you!
